basePath: /
host: borrow-service:50053
info:
  contact: {}
  description: API documentation for the Library Management system - borrow-service
  title: Library Management API - borrow-service
  version: 0.0.6
paths:
  /borrow:
    post:
      consumes:
      - application/json
      description: Allows a user to borrow a book from the library
      parameters:
      - description: User ID
        in: body
        name: user_id
        required: true
        schema:
          type: string
      - description: Book ID
        in: body
        name: book_id
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: Book borrowed successfully
          schema:
            additionalProperties: true
            type: object
        "400":
          description: User ID or Book ID cannot be empty
          schema:
            type: string
        "404":
          description: Book or User not found
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Borrow a book
      tags:
      - borrow
  /borrows/user:
    get:
      consumes:
      - application/json
      description: Retrieves the list of books borrowed by a specific user
      parameters:
      - description: User ID
        in: body
        name: user_id
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: List of borrowed books retrieved successfully
          schema:
            additionalProperties: true
            type: object
        "400":
          description: User ID cannot be empty
          schema:
            type: string
        "404":
          description: No borrow records found for this user
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Get user's borrowed books
      tags:
      - borrow
  /return:
    post:
      consumes:
      - application/json
      description: Allows a user to return a borrowed book to the library
      parameters:
      - description: User ID
        in: body
        name: user_id
        required: true
        schema:
          type: string
      - description: Book ID
        in: body
        name: book_id
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: Book returned successfully
          schema:
            additionalProperties: true
            type: object
        "400":
          description: User ID or Book ID cannot be empty
          schema:
            type: string
        "404":
          description: Book or User not found
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Return a borrowed book
      tags:
      - borrow
swagger: "2.0"
