basePath: /
host: localhost:8080
info:
  contact: {}
  description: API documentation for the Library Management system
  title: Library Management API
  version: 0.0.6
paths:
  /books:
    get:
      consumes:
      - application/json
      description: Get a list of all books
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              additionalProperties: true
              type: object
            type: array
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
      summary: List books
      tags:
      - books
    post:
      consumes:
      - application/json
      description: Add a new book (Admins only)
      parameters:
      - description: Book title
        in: formData
        name: title
        required: true
        type: string
      - description: Book author
        in: formData
        name: author
        required: true
        type: string
      - description: Book category
        in: formData
        name: category
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
      summary: Add a book
      tags:
      - books
  /books/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a book from the library (Admins only)
      parameters:
      - description: Book ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
      summary: Delete a book
      tags:
      - books
    put:
      consumes:
      - application/json
      description: Update a book's information (Admins only)
      parameters:
      - description: Book ID
        in: path
        name: id
        required: true
        type: string
      - description: Book title
        in: formData
        name: title
        type: string
      - description: Book author
        in: formData
        name: author
        type: string
      - description: Book category
        in: formData
        name: category
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
      summary: Update a book
      tags:
      - books
  /books/borrow:
    post:
      consumes:
      - application/json
      description: Borrow a book from the library
      parameters:
      - description: Book ID
        in: formData
        name: book_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
      summary: Borrow a book
      tags:
      - borrow
  /books/return:
    post:
      consumes:
      - application/json
      description: Return a borrowed book to the library
      parameters:
      - description: Book ID
        in: formData
        name: book_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
      summary: Return a book
      tags:
      - borrow
  /books/search:
    get:
      consumes:
      - application/json
      description: Search books by title, author, or category
      parameters:
      - description: Book title
        in: query
        name: title
        type: string
      - description: Book author
        in: query
        name: author
        type: string
      - description: Book category
        in: query
        name: category
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              additionalProperties: true
              type: object
            type: array
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Search books
      tags:
      - books
  /users/login:
    post:
      consumes:
      - application/json
      description: Authenticate user and return JWT token
      parameters:
      - description: User email
        in: formData
        name: email
        required: true
        type: string
      - description: User password
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
      summary: Login user
      tags:
      - users
  /users/profile:
    post:
      consumes:
      - application/json
      description: Retrieves the profile information for the authenticated user
      parameters:
      - description: User email
        in: formData
        name: email
        required: true
        type: string
      - description: Bearer Token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Profile retrieved successfully
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Email cannot be empty
          schema:
            type: string
        "401":
          description: Invalid or missing token
          schema:
            type: string
        "404":
          description: User not found
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Get a user's profile
      tags:
      - users
    put:
      consumes:
      - application/json
      description: Update profile information for the authenticated user
      parameters:
      - description: New name
        in: formData
        name: name
        required: true
        type: string
      - description: New email
        in: formData
        name: email
        required: true
        type: string
      - description: Bearer Token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Profile updated successfully
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Email, name, or email cannot be empty
          schema:
            type: string
        "401":
          description: Invalid or missing token
          schema:
            type: string
        "404":
          description: User not found
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Update a user's profile
      tags:
      - users
  /users/register:
    post:
      consumes:
      - application/json
      description: Register a new user
      parameters:
      - description: User name
        in: formData
        name: name
        required: true
        type: string
      - description: User email
        in: formData
        name: email
        required: true
        type: string
      - description: User password
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
      summary: Register a new user
      tags:
      - users
swagger: "2.0"
