basePath: /
host: auth-service:50054
info:
  contact: {}
  description: API documentation for the Library Management system - auth-service
  title: Library Management API - auth-service
  version: 0.0.6
paths:
  /auth/token:
    post:
      consumes:
      - application/json
      description: Generates a JWT token for the user with the provided user ID and
        role
      parameters:
      - description: User ID
        in: body
        name: user_id
        required: true
        schema:
          type: string
      - description: User role
        in: body
        name: role
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: Token generated successfully
          schema:
            additionalProperties: true
            type: object
        "400":
          description: User ID or Role cannot be empty
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Generate a JWT token for a user with a role
      tags:
      - auth
  /auth/validate:
    post:
      consumes:
      - application/json
      description: Validates the provided JWT token and returns the associated user
        ID and role
      parameters:
      - description: JWT token
        in: body
        name: token
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: Token validated successfully
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Token cannot be empty or is invalid
          schema:
            type: string
        "401":
          description: 'Invalid token: missing userID or role'
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Validate a JWT token
      tags:
      - auth
swagger: "2.0"
